import { pgTable, uniqueIndex, integer, varchar, boolean, timestamp, text, foreignKey, date, smallint, numeric, jsonb, uuid, index, bigint, check, unique, serial, pgSequence } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"


export const authorizationCodesIdSeq = pgSequence("authorization_codes_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const thirdLevelOfficialsMasterlistIdSeq = pgSequence("third_level_officials_masterlist_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const thirdLevelOfficialsProfilingApplicationApplicationIdSeq = pgSequence("third_level_officials_profiling_application_application_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const thirdLevelOfficialsUpdatesTloUidSeq = pgSequence("third_level_officials_updates_TLOUid_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const tloAccomplishmentRecordsIdSeq = pgSequence("tlo_accomplishment_records_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const tloEducationRecordsIdSeq = pgSequence("tlo_education_records_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const tloEligibilityRecordsIdSeq = pgSequence("tlo_eligibility_records_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const tloOtherCoursesIdSeq = pgSequence("tlo_other_courses_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const tloPositionHistoryIdSeq = pgSequence("tlo_position_history_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })
export const tloTrainingRecordsIdSeq = pgSequence("tlo_training_records_id_seq", {  startWith: "1", increment: "1", minValue: "1", maxValue: "9223372036854775807", cache: "1", cycle: false })

export const authorizationCodes = pgTable("authorization_codes", {
	id: integer().default(sql`nextval('authorization_codes_id_seq'::regclass)`).primaryKey().notNull(),
	code: varchar().notNull(),
	role: varchar().notNull(),
	isActive: boolean("is_active").default(true),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	uniqueIndex("authorization_codes_code_key").using("btree", table.code.asc().nullsLast().op("text_ops")),
]);

export const notableAchievements = pgTable("notable_achievements", {
	indexNumber: integer("index_number").primaryKey().notNull(),
	achievement: text().notNull(),
	deleteFlg: integer("delete_flg").default(0),
	createDate: timestamp("create_date", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	editDate: timestamp("edit_date", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
});

export const thirdLevelOfficialsProfiles = pgTable("third_level_officials_profiles", {
	tlid: text().primaryKey().notNull(),
	lastName: text("last_name"),
	firstName: text("first_name"),
	middleName: text("middle_name"),
	suffix: text(),
	gender: text(),
	dateOfBirth: date("date_of_birth"),
	age: smallint(),
	civilStatus: text("civil_status"),
	positionTitle: text("position_title"),
	appointmentDate: date("appointment_date"),
	emtPasser: boolean("emt_passer"),
	emtDate: date("emt_date"),
	cesStage: text("ces_stage"),
	cesConfermentDate: date("ces_conferment_date"),
	totalYearsThirdLevel: numeric("total_years_third_level"),
	previousPositions: jsonb("previous_positions").default([]),
	relevantTrainings: jsonb("relevant_trainings").default([]),
	permanentAddress: text("permanent_address"),
	highestEducation: text("highest_education"),
	educationProgram: text("education_program"),
	educationYearGraduated: smallint("education_year_graduated"),
	notableAchievements: text("notable_achievements"),
	performanceRatingIpcrf: text("performance_rating_ipcrf"),
	performanceRatingCespes: text("performance_rating_cespes"),
	photoBinaryId: uuid("photo_binary_id"),
	pdsBinaryId: uuid("pds_binary_id"),
	profileWordBinaryId: uuid("profile_word_binary_id"),
	profilePptBinaryId: uuid("profile_ppt_binary_id"),
	serviceRecordsBinaryId: uuid("service_records_binary_id"),
	pendingAdminCase: text("pending_admin_case"),
	ombudsmanCase: text("ombudsman_case"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	tloMasterlistId: integer("tlo_masterlist_id"),
}, (table) => [
	foreignKey({
			columns: [table.tloMasterlistId],
			foreignColumns: [tloMasterlist.id],
			name: "third_level_officials_profiles_tlo_masterlist_id_fkey"
		}),
]);

export const thirdLevelOfficialsMasterlist = pgTable("third_level_officials_masterlist", {
	id: integer().default(sql`nextval('third_level_officials_masterlist_id_seq'::regclass)`).primaryKey().notNull(),
	tlid: text(),
	sortIndex: integer("sort_index"),
	strand: text(),
	office: text(),
	name: text(),
	position: text(),
	email: text(),
	altEmail1: text("alt_email_1"),
	altEmail2: text("alt_email_2"),
	contactDetails: text("contact_details"),
	altContactDetails1: text("alt_contact_details_1"),
	altContactDetails2: text("alt_contact_details_2"),
	assignmentDate: date("assignment_date"),
	remarks: text(),
	status: text(),
	changeType: text("change_type"),
	updatedBy: text("updated_by"),
	createdAt: timestamp("created_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	updatedAt: timestamp("updated_at", { mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
});

export const thirdLevelOfficialMasterlist = pgTable("third_level_official_masterlist", {
	tlOid: text("TLOid").primaryKey().notNull(),
	firstName: text("first_name"),
	lastName: text("last_name"),
	middleName: text("middle_name"),
	suffix: text(),
	gender: text(),
	dateOfBirth: date("date_of_birth"),
	civilStatus: text("civil_status"),
	positionTitle: text("position_title"),
	office: text(),
	strand: text(),
	status: text(),
	email: text(),
	altEmail1: text("alt_email_1"),
	altEmail2: text("alt_email_2"),
	contactDetails: text("contact_details"),
	altContactDetails1: text("alt_contact_details_1"),
	altContactDetails2: text("alt_contact_details_2"),
	permanentAddress: text("permanent_address"),
	emtPasser: boolean("emt_passer"),
	emtDate: date("emt_date"),
	cesStage: text("ces_stage"),
	cesConfermentDate: date("ces_conferment_date"),
	totalYearsThirdLevel: numeric("total_years_third_level"),
	managerialExperienceTotal: text("managerial_experience_total"),
	performanceRating1: text("performance_rating_1"),
	performanceRating1Period: text("performance_rating_1_period"),
	performanceRating2: text("performance_rating_2"),
	performanceRating2Period: text("performance_rating_2_period"),
	cespes1Rating: varchar("cespes_1_rating"),
	cespes2Rating: varchar("cespes_2_rating"),
	cespesRating1Period: varchar("cespes_rating_1_period"),
	cespesRating2Period: varchar("cespes_rating_2_period"),
	notableAchievements: jsonb("notable_achievements").default([]),
	totalTrainingHours: numeric("total_training_hours"),
	performanceRatingIpcrf: text("performance_rating_ipcrf"),
	performanceRatingCespes: text("performance_rating_cespes"),
	photoBinaryId: uuid("photo_binary_id"),
	pdsBinaryId: uuid("pds_binary_id"),
	profileWordBinaryId: uuid("profile_word_binary_id"),
	profilePptBinaryId: uuid("profile_ppt_binary_id"),
	serviceRecordsBinaryId: uuid("service_records_binary_id"),
	pendingAdminCase: text("pending_admin_case"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }),
	appointmentDate: date("appointment_date"),
	age: smallint(),
	dpaConsentedAt: timestamp("dpa_consented_at", { withTimezone: true, mode: 'string' }),
	effectivityDate: timestamp("effectivity_date", { mode: 'string' }),
	reassignTargetTloid: varchar("reassign_target_tloid"),
	reassignAssigneeTloid: varchar("reassign_assignee_tloid"),
	region: varchar(),
	sandiganbayanClearanceBinaryId: varchar("sandiganbayan_clearance_binary_id"),
	nbiClearanceBinaryId: varchar("nbi_clearance_binary_id"),
	cscClearanceBinaryId: varchar("csc_clearance_binary_id"),
	ombudsmanClearanceBinaryId: varchar("ombudsman_clearance_binary_id"),
	guiltyAdminDetails: text("guilty_admin_details"),
	criminallyChargedDetails: text("criminally_charged_details"),
	convictedCrimeDetails: text("convicted_crime_details"),
	designation: text(),
	isOic: boolean("is_oic").default(false),
	division: varchar(),
	sortIndex: integer("sort_index").default(0),
	ombudsmanCase: text("ombudsman_case"),
	nationality: text(),
	religion: text(),
	bloodType: text("blood_type"),
	dependents: text(),
	height: text(),
	weight: text(),
	temporaryAddress: varchar("temporary_address"),
	executiveSummaryBinaryId: text("executive_summary_binary_id"),
	performanceRating3: text("performance_rating_3"),
	performanceRating3Period: text("performance_rating_3_period"),
	employmentStatus: text("employment_status"),
	assignment: text(),
	dateOfAssignment: text("date_of_assignment"),
	isTestaccount: boolean("is_testaccount").default(false).notNull(),
	reassignmentOrderBinaryId: uuid("reassignment_order_binary_id"),
	appointmentStatus: text("appointment_status"),
	plantillaItemNo: text("plantilla_item_no"),
}, (table) => [
	index("idx_tlo_masterlist_is_testaccount").using("btree", table.isTestaccount.asc().nullsLast().op("bool_ops")),
	index("idx_tlo_masterlist_status").using("btree", table.status.asc().nullsLast().op("text_ops")),
	index("idx_tlo_masterlist_strand").using("btree", table.strand.asc().nullsLast().op("text_ops")),
]);

export const thirdLevelOfficialsUpdates = pgTable("third_level_officials_updates", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	tloUid: bigint("TLOUid", { mode: "number" }).default(sql`nextval('"third_level_officials_updates_TLOUid_seq"'::regclass)`).primaryKey().notNull(),
	tlOid: text("TLOid").notNull(),
	changeType: text("change_type"),
	updatedBy: text("updated_by"),
	remarks: text(),
	sortIndex: integer("sort_index"),
	lastName: text("last_name"),
	firstName: text("first_name"),
	middleName: text("middle_name"),
	suffix: text(),
	gender: text(),
	dateOfBirth: date("date_of_birth"),
	civilStatus: text("civil_status"),
	strand: text(),
	office: text(),
	designation: text(),
	assignment: text(),
	dateOfAssignment: text("date_of_assignment"),
	positionTitle: text("position_title"),
	status: text(),
	email: text(),
	altEmail1: text("alt_email_1"),
	altEmail2: text("alt_email_2"),
	contactDetails: text("contact_details"),
	altContactDetails1: text("alt_contact_details_1"),
	altContactDetails2: text("alt_contact_details_2"),
	permanentAddress: text("permanent_address"),
	emtPasser: boolean("emt_passer"),
	emtDate: date("emt_date"),
	cesStage: text("ces_stage"),
	cesConfermentDate: date("ces_conferment_date"),
	previousPositions: jsonb("previous_positions").default([]),
	totalYearsThirdLevel: numeric("total_years_third_level"),
	highestEducation: text("highest_education"),
	educationProgram: text("education_program"),
	educationYearGraduated: smallint("education_year_graduated"),
	relevantTrainings: jsonb("relevant_trainings").default([]),
	notableAchievements: text("notable_achievements"),
	performanceRatingIpcrf: text("performance_rating_ipcrf"),
	performanceRatingCespes: text("performance_rating_cespes"),
	photoBinaryId: uuid("photo_binary_id"),
	pdsBinaryId: uuid("pds_binary_id"),
	profileWordBinaryId: uuid("profile_word_binary_id"),
	profilePptBinaryId: uuid("profile_ppt_binary_id"),
	serviceRecordsBinaryId: uuid("service_records_binary_id"),
	pendingAdminCase: text("pending_admin_case"),
	ombudsmanCase: text("ombudsman_case"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	tlid: text(),
	effectivityDate: timestamp("effectivity_date", { mode: 'string' }),
	vacateReason: varchar("vacate_reason"),
	region: varchar(),
	division: varchar(),
}, (table) => [
	index("idx_tlm_updates_tlid").using("btree", table.tlid.asc().nullsLast().op("text_ops")),
	index("idx_tlo_updates_tloid").using("btree", table.tlOid.asc().nullsLast().op("text_ops")),
]);

export const tloEducationRecords = pgTable("tlo_education_records", {
	id: integer().default(sql`nextval('tlo_education_records_id_seq'::regclass)`).primaryKey().notNull(),
	sourceTable: varchar("source_table").notNull(),
	tloId: varchar("tlo_id").notNull(),
	level: varchar().notNull(),
	degree: text().default('').notNull(),
	institution: text(),
	yearGraduated: integer("year_graduated"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	personnelId: uuid("personnel_id"),
}, (table) => [
	index("idx_tlo_edu_level").using("btree", table.level.asc().nullsLast().op("text_ops")),
	index("idx_tlo_edu_personnel").using("btree", table.personnelId.asc().nullsLast().op("uuid_ops")),
	index("idx_tlo_edu_source_tloid").using("btree", table.sourceTable.asc().nullsLast().op("text_ops"), table.tloId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.personnelId],
			foreignColumns: [tloPersonnel.id],
			name: "tlo_education_records_personnel_id_fkey"
		}),
]);

export const thirdLevelOfficialsProfilingApplication = pgTable("third_level_officials_profiling_application", {
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	applicationId: bigint("application_id", { mode: "number" }).default(sql`nextval('third_level_officials_profiling_application_application_id_seq'::regclass)`).primaryKey().notNull(),
	appTloid: text("app_tloid"),
	profilingStatus: text("profiling_status"),
	applicationStatus: text("application_status"),
	positionAppliedFor: text("position_applied_for"),
	targetTloid: text("target_tloid"),
	submittedAt: timestamp("submitted_at", { withTimezone: true, mode: 'string' }),
	reviewedAt: timestamp("reviewed_at", { withTimezone: true, mode: 'string' }),
	reviewedBy: text("reviewed_by"),
	denialReason: text("denial_reason"),
	lastName: text("last_name"),
	firstName: text("first_name"),
	middleName: text("middle_name"),
	suffix: text(),
	gender: text(),
	dateOfBirth: date("date_of_birth"),
	civilStatus: text("civil_status"),
	strand: text(),
	office: text(),
	designation: text(),
	assignment: text(),
	dateOfAssignment: text("date_of_assignment"),
	positionTitle: text("position_title"),
	status: text(),
	email: text(),
	altEmail1: text("alt_email_1"),
	altEmail2: text("alt_email_2"),
	contactDetails: text("contact_details"),
	altContactDetails1: text("alt_contact_details_1"),
	altContactDetails2: text("alt_contact_details_2"),
	permanentAddress: text("permanent_address"),
	emtPasser: boolean("emt_passer"),
	emtDate: date("emt_date"),
	cesStage: text("ces_stage"),
	cesConfermentDate: date("ces_conferment_date"),
	totalYearsThirdLevel: numeric("total_years_third_level"),
	managerialExperienceTotal: varchar("managerial_experience_total"),
	performanceRating1: varchar("performance_rating_1"),
	performanceRating1Period: varchar("performance_rating_1_period"),
	performanceRating2: varchar("performance_rating_2"),
	performanceRating2Period: varchar("performance_rating_2_period"),
	cespes1Rating: varchar("cespes_1_rating"),
	cespes2Rating: varchar("cespes_2_rating"),
	cespesRating1Period: varchar("cespes_rating_1_period"),
	cespesRating2Period: varchar("cespes_rating_2_period"),
	notableAchievements: jsonb("notable_achievements").default([]),
	totalTrainingHours: numeric("total_training_hours"),
	performanceRatingIpcrf: text("performance_rating_ipcrf"),
	performanceRatingCespes: text("performance_rating_cespes"),
	photoBinaryId: uuid("photo_binary_id"),
	pdsBinaryId: uuid("pds_binary_id"),
	profileWordBinaryId: uuid("profile_word_binary_id"),
	profilePptBinaryId: uuid("profile_ppt_binary_id"),
	serviceRecordsBinaryId: uuid("service_records_binary_id"),
	pendingAdminCase: text("pending_admin_case"),
	dpaConsentedAt: timestamp("dpa_consented_at", { withTimezone: true, mode: 'string' }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }),
	targetTlOid: text("target_TLOid"),
	sandiganbayanClearanceBinaryId: varchar("sandiganbayan_clearance_binary_id"),
	nbiClearanceBinaryId: varchar("nbi_clearance_binary_id"),
	cscClearanceBinaryId: varchar("csc_clearance_binary_id"),
	ombudsmanClearanceBinaryId: varchar("ombudsman_clearance_binary_id"),
	guiltyAdminDetails: text("guilty_admin_details"),
	criminallyChargedDetails: text("criminally_charged_details"),
	convictedCrimeDetails: text("convicted_crime_details"),
	isOic: boolean("is_oic").default(false),
	age: integer(),
	appointmentDate: timestamp("appointment_date", { mode: 'string' }),
	bloodType: text("blood_type"),
	dependents: text(),
	height: text(),
	weight: text(),
	temporaryAddress: varchar("temporary_address"),
	executiveSummaryBinaryId: text("executive_summary_binary_id"),
	performanceRating3: text("performance_rating_3"),
	performanceRating3Period: text("performance_rating_3_period"),
	nationality: text(),
	employmentStatus: text("employment_status"),
	religion: text(),
	educationDegrees: jsonb("education_degrees"),
	isTestaccount: boolean("is_testaccount").default(false).notNull(),
	appointmentStatus: text("appointment_status"),
}, (table) => [
	index("idx_tlo_app_is_testaccount").using("btree", table.isTestaccount.asc().nullsLast().op("bool_ops")),
	index("idx_tlopa_email").using("btree", sql`lower(email)`),
	index("idx_tlopa_status").using("btree", table.applicationStatus.asc().nullsLast().op("text_ops")),
]);

export const tloOtherCourses = pgTable("tlo_other_courses", {
	id: integer().default(sql`nextval('tlo_other_courses_id_seq'::regclass)`).primaryKey().notNull(),
	sourceTable: varchar("source_table").notNull(),
	tloId: varchar("tlo_id").notNull(),
	courseTitle: text("course_title").default('').notNull(),
	details: text(),
	institution: text(),
	dateFrom: date("date_from"),
	dateTo: date("date_to"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	deleteFlg: varchar("delete_flg").default('No').notNull(),
	personnelId: uuid("personnel_id"),
}, (table) => [
	index("idx_other_courses_delete_flg").using("btree", table.deleteFlg.asc().nullsLast().op("text_ops")),
	index("idx_tlo_courses_source_tloid").using("btree", table.sourceTable.asc().nullsLast().op("text_ops"), table.tloId.asc().nullsLast().op("text_ops")),
	index("idx_tlo_other_personnel").using("btree", table.personnelId.asc().nullsLast().op("uuid_ops")),
	foreignKey({
			columns: [table.personnelId],
			foreignColumns: [tloPersonnel.id],
			name: "tlo_other_courses_personnel_id_fkey"
		}),
]);

export const tloPersonnel = pgTable("tlo_personnel", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	legacyTloId: varchar("legacy_tlo_id", { length: 50 }),
	prefix: varchar({ length: 50 }),
	firstName: varchar("first_name", { length: 150 }).notNull(),
	middleName: varchar("middle_name", { length: 150 }),
	lastName: varchar("last_name", { length: 150 }).notNull(),
	suffix: varchar({ length: 50 }),
	gender: varchar({ length: 20 }),
	dateOfBirth: date("date_of_birth"),
	civilStatus: varchar("civil_status", { length: 50 }),
	email: varchar({ length: 255 }),
	altEmail1: varchar("alt_email_1", { length: 255 }),
	altEmail2: varchar("alt_email_2", { length: 255 }),
	contactDetails: varchar("contact_details", { length: 255 }),
	altContactDetails1: varchar("alt_contact_details_1", { length: 255 }),
	altContactDetails2: varchar("alt_contact_details_2", { length: 255 }),
	permanentAddress: text("permanent_address"),
	temporaryAddress: text("temporary_address"),
	nationality: text(),
	religion: text(),
	bloodType: text("blood_type"),
	dependents: text(),
	height: text(),
	weight: text(),
	age: smallint(),
	dpaConsentedAt: timestamp("dpa_consented_at", { withTimezone: true, mode: 'string' }),
	emtPasser: boolean("emt_passer"),
	emtDate: date("emt_date"),
	cesStage: text("ces_stage"),
	cesConfermentDate: date("ces_conferment_date"),
	totalYearsThirdLevel: numeric("total_years_third_level"),
	managerialExperienceTotal: text("managerial_experience_total"),
	performanceRating1: text("performance_rating_1"),
	performanceRating1Period: text("performance_rating_1_period"),
	performanceRating2: text("performance_rating_2"),
	performanceRating2Period: text("performance_rating_2_period"),
	performanceRating3: text("performance_rating_3"),
	performanceRating3Period: text("performance_rating_3_period"),
	cespes1Rating: text("cespes_1_rating"),
	cespes2Rating: text("cespes_2_rating"),
	cespesRating1Period: text("cespes_rating_1_period"),
	cespesRating2Period: text("cespes_rating_2_period"),
	performanceRatingIpcrf: text("performance_rating_ipcrf"),
	performanceRatingCespes: text("performance_rating_cespes"),
	pendingAdminCase: text("pending_admin_case"),
	ombudsmanCase: text("ombudsman_case"),
	guiltyAdminDetails: text("guilty_admin_details"),
	criminallyChargedDetails: text("criminally_charged_details"),
	convictedCrimeDetails: text("convicted_crime_details"),
	sandiganbayanClearanceBinaryId: varchar("sandiganbayan_clearance_binary_id", { length: 255 }),
	nbiClearanceBinaryId: varchar("nbi_clearance_binary_id", { length: 255 }),
	cscClearanceBinaryId: varchar("csc_clearance_binary_id", { length: 255 }),
	ombudsmanClearanceBinaryId: varchar("ombudsman_clearance_binary_id", { length: 255 }),
	photoBinaryId: uuid("photo_binary_id"),
	pdsBinaryId: uuid("pds_binary_id"),
	profileWordBinaryId: uuid("profile_word_binary_id"),
	profilePptBinaryId: uuid("profile_ppt_binary_id"),
	serviceRecordsBinaryId: uuid("service_records_binary_id"),
	executiveSummaryBinaryId: text("executive_summary_binary_id"),
	notableAchievements: jsonb("notable_achievements").default([]),
	totalTrainingHours: numeric("total_training_hours"),
	isTestaccount: boolean("is_testaccount").default(false).notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_tlo_personnel_is_testaccount").using("btree", table.isTestaccount.asc().nullsLast().op("bool_ops")),
]);

export const tloUsers = pgTable("tlo_users", {
	uid: text().primaryKey().notNull(),
	email: text(),
	role: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`),
	firstName: text("first_name"),
	lastName: text("last_name"),
	region: text(),
	division: text(),
	province: text(),
	city: text(),
	barangay: text(),
	office: text(),
	position: text(),
	disabled: boolean().default(false),
	contactNumber: text("contact_number"),
	altEmail: text("alt_email"),
	accountCategory: text("account_category"),
	passwordHash: text("password_hash"),
	passwordSalt: text("password_salt"),
	hashVersion: text("hash_version").default('firebase'),
	passcode: text(),
	iern: text(),
	registrantType: text("registrant_type"),
	schoolId: text("school_id"),
	hasSeenNexusTutorial: boolean("has_seen_nexus_tutorial").default(false),
	registrationStatus: varchar("registration_status").default('Valid'),
	isTestaccount: boolean("is_testaccount").default(false).notNull(),
	assignedRegion: text("assigned_region"),
	assignedDivision: text("assigned_division"),
	divisionMultiple: text("division_multiple").array().default([""]),
	assignment: text(),
	dateOfAssignment: text("date_of_assignment"),
}, (table) => [
	index("idx_tlo_users_division_multiple").using("gin", table.divisionMultiple.asc().nullsLast().op("array_ops")),
	index("idx_tlo_users_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	index("idx_tlo_users_email_lower").using("btree", sql`lower(email)`),
	index("idx_tlo_users_iern").using("btree", table.iern.asc().nullsLast().op("text_ops")),
	index("idx_tlo_users_is_testaccount").using("btree", table.isTestaccount.asc().nullsLast().op("bool_ops")),
	uniqueIndex("idx_tlo_users_school_id").using("btree", table.schoolId.asc().nullsLast().op("text_ops")).where(sql`(school_id IS NOT NULL)`),
	uniqueIndex("idx_tlo_users_school_id_valid").using("btree", table.schoolId.asc().nullsLast().op("text_ops")).where(sql`(((registration_status)::text = 'Valid'::text) AND (school_id IS NOT NULL))`),
]);

export const unifiedBinaries = pgTable("unified_binaries", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	hash: text(),
	mimeType: text("mime_type"),
	sizeBytes: integer("size_bytes"),
	azureBlobUrl: text("azure_blob_url"),
	createdAt: timestamp("created_at", { mode: 'string' }).defaultNow(),
}, (table) => [
	uniqueIndex("idx_unified_binaries_hash").using("btree", table.hash.asc().nullsLast().op("text_ops")),
]);

export const verificationCodes = pgTable("verification_codes", {
	email: varchar().primaryKey().notNull(),
	code: varchar().notNull(),
	expiresAt: timestamp("expires_at", { mode: 'string' }).default(sql`(now() + '00:10:00'::interval)`),
});

export const tloAccomplishmentRecords = pgTable("tlo_accomplishment_records", {
	id: integer().default(sql`nextval('tlo_accomplishment_records_id_seq'::regclass)`).primaryKey().notNull(),
	sourceTable: varchar("source_table").notNull(),
	tloId: varchar("tlo_id").notNull(),
	description: text().default('').notNull(),
	awardYear: integer("award_year"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	deleteFlg: varchar("delete_flg").default('No').notNull(),
	personnelId: uuid("personnel_id"),
}, (table) => [
	index("idx_accomplishment_delete_flg").using("btree", table.deleteFlg.asc().nullsLast().op("text_ops")),
	index("idx_tlo_accomp_personnel").using("btree", table.personnelId.asc().nullsLast().op("uuid_ops")),
	index("idx_tlo_accomp_source_tloid").using("btree", table.sourceTable.asc().nullsLast().op("text_ops"), table.tloId.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.personnelId],
			foreignColumns: [tloPersonnel.id],
			name: "tlo_accomplishment_records_personnel_id_fkey"
		}),
]);

export const tloEligibilityRecords = pgTable("tlo_eligibility_records", {
	id: integer().default(sql`nextval('tlo_eligibility_records_id_seq'::regclass)`).primaryKey().notNull(),
	sourceTable: varchar("source_table").notNull(),
	tloId: varchar("tlo_id").notNull(),
	eligibilityType: text("eligibility_type").default('').notNull(),
	rating: varchar(),
	confermentDate: date("conferment_date"),
	placeOfAssignment: text("place_of_assignment"),
	details: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	deleteFlg: varchar("delete_flg").default('No').notNull(),
	personnelId: uuid("personnel_id"),
}, (table) => [
	index("idx_eligibility_delete_flg").using("btree", table.deleteFlg.asc().nullsLast().op("text_ops")),
	index("idx_tlo_elig_personnel").using("btree", table.personnelId.asc().nullsLast().op("uuid_ops")),
	index("idx_tlo_elig_source_tloid").using("btree", table.sourceTable.asc().nullsLast().op("text_ops"), table.tloId.asc().nullsLast().op("text_ops")),
	index("idx_tlo_elig_type").using("btree", table.eligibilityType.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.personnelId],
			foreignColumns: [tloPersonnel.id],
			name: "tlo_eligibility_records_personnel_id_fkey"
		}),
]);

export const tloTrainingRecords = pgTable("tlo_training_records", {
	id: integer().default(sql`nextval('tlo_training_records_id_seq'::regclass)`).primaryKey().notNull(),
	sourceTable: varchar("source_table").notNull(),
	tloId: varchar("tlo_id").notNull(),
	trainingName: text("training_name").default('').notNull(),
	hours: integer(),
	inclusiveDateStart: date("inclusive_date_start"),
	inclusiveDateEnd: date("inclusive_date_end"),
	conductedBy: text("conducted_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	deleteFlg: varchar("delete_flg").default('No').notNull(),
	personnelId: uuid("personnel_id"),
}, (table) => [
	index("idx_tlo_train_hours").using("btree", table.tloId.asc().nullsLast().op("text_ops"), table.hours.asc().nullsLast().op("int4_ops")),
	index("idx_tlo_train_personnel").using("btree", table.personnelId.asc().nullsLast().op("uuid_ops")),
	index("idx_tlo_train_source_tloid").using("btree", table.sourceTable.asc().nullsLast().op("text_ops"), table.tloId.asc().nullsLast().op("text_ops")),
	index("idx_training_delete_flg").using("btree", table.deleteFlg.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.personnelId],
			foreignColumns: [tloPersonnel.id],
			name: "tlo_training_records_personnel_id_fkey"
		}),
]);

export const tloPositionHistory = pgTable("tlo_position_history", {
	id: integer().default(sql`nextval('tlo_position_history_id_seq'::regclass)`).primaryKey().notNull(),
	sourceTable: varchar("source_table").notNull(),
	tloId: varchar("tlo_id").notNull(),
	positionName: text("position_name").default('').notNull(),
	office: text(),
	strand: text(),
	division: text(),
	region: text(),
	inclusiveDateStart: date("inclusive_date_start"),
	inclusiveDateEnd: date("inclusive_date_end"),
	oicPositions: jsonb("oic_positions"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	deleteFlg: varchar("delete_flg").default('No').notNull(),
	reassignmentOrderBinaryId: uuid("reassignment_order_binary_id"),
	status: varchar({ length: 50 }).default('Inactive').notNull(),
	oic: boolean().default(false).notNull(),
	designation: text(),
}, (table) => [
	index("idx_position_history_delete_flg").using("btree", table.deleteFlg.asc().nullsLast().op("text_ops")),
	index("idx_tlo_pos_dates").using("btree", table.tloId.asc().nullsLast().op("date_ops"), table.inclusiveDateStart.desc().nullsFirst().op("date_ops"), table.inclusiveDateEnd.desc().nullsFirst().op("text_ops")),
	index("idx_tlo_pos_source_tloid").using("btree", table.sourceTable.asc().nullsLast().op("text_ops"), table.tloId.asc().nullsLast().op("text_ops")),
	index("idx_tlo_pos_status_oic").using("btree", table.status.asc().nullsLast().op("text_ops"), table.oic.asc().nullsLast().op("bool_ops")),
	check("chk_tlo_position_history_status", sql`(status)::text = ANY ((ARRAY['Active'::character varying, 'Inactive'::character varying])::text[])`),
]);

export const cesPlantilla = pgTable("ces_plantilla", {
	id: serial().primaryKey().notNull(),
	sourceRowNumber: integer("source_row_number").notNull(),
	officeBureauDivision: text("office_bureau_division"),
	region: text(),
	positionTitle: text("position_title"),
	dbmItemNo: text("dbm_item_no"),
	salaryGrade: varchar("salary_grade", { length: 10 }),
	incumbentName: text("incumbent_name"),
	statusOfAppointment: text("status_of_appointment"),
	isVacant: boolean("is_vacant").default(false),
	isSectionHeader: boolean("is_section_header").default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_ces_plantilla_dbm_item_no").using("btree", table.dbmItemNo.asc().nullsLast().op("text_ops")),
	index("idx_ces_plantilla_is_vacant").using("btree", table.isVacant.asc().nullsLast().op("bool_ops")),
	index("idx_ces_plantilla_position").using("btree", table.positionTitle.asc().nullsLast().op("text_ops")),
	index("idx_ces_plantilla_region").using("btree", table.region.asc().nullsLast().op("text_ops")),
	index("idx_ces_plantilla_source_row").using("btree", table.sourceRowNumber.asc().nullsLast().op("int4_ops")),
	unique("ces_plantilla_report_source_row_number_key").on(table.sourceRowNumber),
]);

export const tloPlantilla = pgTable("tlo_plantilla", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	permanentItemNo: varchar("permanent_item_no", { length: 100 }),
	firstName: varchar("first_name", { length: 150 }),
	middleName: varchar("middle_name", { length: 150 }),
	lastName: varchar("last_name", { length: 150 }),
	suffix: varchar({ length: 50 }),
	prefix: varchar({ length: 50 }),
	gender: varchar({ length: 50 }),
	employmentType: varchar("employment_type", { length: 50 }).default('PLANTILLA').notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	salary: numeric({ precision: 12, scale:  2 }),
	salaryGrade: varchar("salary_grade", { length: 50 }),
}, (table) => [
	index("idx_tlo_plantilla_employment").using("btree", table.employmentType.asc().nullsLast().op("text_ops")),
	index("idx_tlo_plantilla_names").using("btree", table.lastName.asc().nullsLast().op("text_ops"), table.firstName.asc().nullsLast().op("text_ops")),
	uniqueIndex("idx_tlo_plantilla_permanent_item_no").using("btree", table.permanentItemNo.asc().nullsLast().op("text_ops")).where(sql`((permanent_item_no IS NOT NULL) AND ((permanent_item_no)::text <> ''::text) AND (upper((permanent_item_no)::text) <> ALL (ARRAY['NEW ITEM'::text, 'DETAILED'::text, 'N/A'::text, 'N/A (DETAILED)'::text])))`),
	index("idx_tlo_plantilla_salary_grade").using("btree", table.salaryGrade.asc().nullsLast().op("text_ops")),
]);

export const tloProfile = pgTable("tlo_profile", {
	id: serial().primaryKey().notNull(),
	dateOfBirth: date("date_of_birth"),
	civilStatus: varchar("civil_status", { length: 50 }),
	tin: varchar({ length: 50 }),
	gsis: varchar({ length: 50 }),
	pagibig: varchar({ length: 50 }),
	philhealth: varchar({ length: 50 }),
	email: varchar({ length: 255 }),
	altEmail1: varchar("alt_email_1", { length: 255 }),
	altEmail2: varchar("alt_email_2", { length: 255 }),
	contactDetails: varchar("contact_details", { length: 255 }),
	altContactDetails1: varchar("alt_contact_details_1", { length: 255 }),
	altContactDetails2: varchar("alt_contact_details_2", { length: 255 }),
	permanentAddress: text("permanent_address"),
	temporaryAddress: text("temporary_address"),
	nationality: text(),
	religion: text(),
	bloodType: text("blood_type"),
	dependents: text(),
	height: text(),
	weight: text(),
	age: smallint(),
	dpaConsentedAt: timestamp("dpa_consented_at", { withTimezone: true, mode: 'string' }),
	emtPasser: boolean("emt_passer"),
	emtDate: date("emt_date"),
	cesStage: text("ces_stage"),
	cesConfermentDate: date("ces_conferment_date"),
	totalYearsThirdLevel: numeric("total_years_third_level"),
	managerialExperienceTotal: text("managerial_experience_total"),
	performanceRating1: text("performance_rating_1"),
	performanceRating1Period: text("performance_rating_1_period"),
	performanceRating2: text("performance_rating_2"),
	performanceRating2Period: text("performance_rating_2_period"),
	performanceRating3: text("performance_rating_3"),
	performanceRating3Period: text("performance_rating_3_period"),
	cespes1Rating: text("cespes_1_rating"),
	cespes2Rating: text("cespes_2_rating"),
	cespesRating1Period: text("cespes_rating_1_period"),
	cespesRating2Period: text("cespes_rating_2_period"),
	performanceRatingIpcrf: text("performance_rating_ipcrf"),
	performanceRatingCespes: text("performance_rating_cespes"),
	pendingAdminCase: text("pending_admin_case"),
	ombudsmanCase: text("ombudsman_case"),
	guiltyAdminDetails: text("guilty_admin_details"),
	criminallyChargedDetails: text("criminally_charged_details"),
	convictedCrimeDetails: text("convicted_crime_details"),
	sandiganbayanClearanceBinaryId: varchar("sandiganbayan_clearance_binary_id", { length: 255 }),
	nbiClearanceBinaryId: varchar("nbi_clearance_binary_id", { length: 255 }),
	cscClearanceBinaryId: varchar("csc_clearance_binary_id", { length: 255 }),
	ombudsmanClearanceBinaryId: varchar("ombudsman_clearance_binary_id", { length: 255 }),
	photoBinaryId: uuid("photo_binary_id"),
	pdsBinaryId: uuid("pds_binary_id"),
	profileWordBinaryId: uuid("profile_word_binary_id"),
	profilePptBinaryId: uuid("profile_ppt_binary_id"),
	serviceRecordsBinaryId: uuid("service_records_binary_id"),
	executiveSummaryBinaryId: text("executive_summary_binary_id"),
	notableAchievements: jsonb("notable_achievements").default([]),
	totalTrainingHours: numeric("total_training_hours"),
	isTestaccount: boolean("is_testaccount").default(false),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	tloMasterlistId: integer("tlo_masterlist_id"),
}, (table) => [
	index("idx_tlo_profile_email").using("btree", table.email.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.tloMasterlistId],
			foreignColumns: [tloMasterlist.id],
			name: "tlo_profile_tlo_masterlist_id_fkey"
		}),
]);



export const tloPositions = pgTable("tlo_positions", {
	id: serial().primaryKey().notNull(),
	positionTitle: varchar("position_title", { length: 150 }).notNull(),
	salaryGrade: varchar("salary_grade", { length: 20 }),
	description: text(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	positionCode: varchar("position_code", { length: 100 }),
	region: varchar({ length: 255 }),
	division: varchar({ length: 255 }),
	bureau: varchar({ length: 255 }),
}, (table) => [
	index("idx_tlo_positions_bureau").using("btree", table.bureau.asc().nullsLast().op("text_ops")),
	index("idx_tlo_positions_code").using("btree", table.positionCode.asc().nullsLast().op("text_ops")),
	index("idx_tlo_positions_division").using("btree", table.division.asc().nullsLast().op("text_ops")),
	index("idx_tlo_positions_region").using("btree", table.region.asc().nullsLast().op("text_ops")),
	index("idx_tlo_positions_title").using("btree", table.positionTitle.asc().nullsLast().op("text_ops")),
]);

export const tloMasterlist = pgTable("tlo_masterlist", {
	id: serial().primaryKey().notNull(),
	tloid: varchar({ length: 50 }).notNull(),
	firstName: varchar("first_name", { length: 255 }),
	lastName: varchar("last_name", { length: 255 }),
	middleName: varchar("middle_name", { length: 255 }),
	suffix: varchar({ length: 50 }),
	gender: varchar({ length: 50 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
}, (table) => [
	index("idx_tlo_masterlist_gender").using("btree", table.gender.asc().nullsLast().op("text_ops")),
	index("idx_tlo_masterlist_last_name").using("btree", table.lastName.asc().nullsLast().op("text_ops")),
	index("idx_tlo_masterlist_lower_tloid").using("btree", table.tloid.asc().nullsLast().op("text_ops")),
	index("idx_tlo_masterlist_tloid").using("btree", table.tloid.asc().nullsLast().op("text_ops")),
	unique("uq_tlo_masterlist_tloid").on(table.tloid),
]);

export const tloAssignmentsBackup20260915 = pgTable("tlo_assignments_backup_20260915", {
	id: integer(),
	personnelId: uuid("personnel_id"),
	itemNumber: varchar("item_number", { length: 100 }),
	positionId: integer("position_id"),
	positionCode: varchar("position_code", { length: 100 }),
	salaryGrade: varchar("salary_grade"),
	positionTitle: varchar("position_title", { length: 255 }),
	region: varchar({ length: 150 }),
	division: varchar({ length: 150 }),
	office: varchar({ length: 150 }),
	strand: varchar({ length: 150 }),
	designation: text(),
	assignmentType: text("assignment_type"),
	status: text(),
	isActive: boolean("is_active"),
	assignedAt: timestamp("assigned_at", { withTimezone: true, mode: 'string' }),
	unassignedAt: timestamp("unassigned_at", { withTimezone: true, mode: 'string' }),
	startDate: date("start_date"),
	endDate: date("end_date"),
	reassignmentOrderBinaryId: uuid("reassignment_order_binary_id"),
	remarks: text(),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }),
	oic: boolean(),
});

export const tloAssignmentsBackupSchemaRefactor = pgTable("tlo_assignments_backup_schema_refactor", {
	id: integer(),
	tloMasterlistId: varchar("tlo_masterlist_id", { length: 255 }),
	tloPositionId: varchar("tlo_position_id", { length: 255 }),
	status: varchar({ length: 20 }),
	capacity: varchar({ length: 20 }),
	startDate: date("start_date"),
	endDate: date("end_date"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }),
});

export const tloAssignments = pgTable("tlo_assignments", {
	id: serial().primaryKey().notNull(),
	status: varchar({ length: 20 }).default('Active').notNull(),
	capacity: varchar({ length: 20 }).default('Full').notNull(),
	startDate: date("start_date").default(sql`CURRENT_DATE`).notNull(),
	endDate: date("end_date"),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).default(sql`CURRENT_TIMESTAMP`).notNull(),
	tloMasterlistId: integer("tlo_masterlist_id"),
	tloPositionId: varchar("tlo_position_id", { length: 100 }),
	positionId: integer("position_id"),
	designation: text(),
	remarks: text(),
	reassignmentOrderBinaryId: uuid("reassignment_order_binary_id"),
	createdBy: text("created_by"),
	updatedBy: text("updated_by"),
}, (table) => [
	index("idx_tlo_assignments_active").using("btree", table.tloMasterlistId.asc().nullsLast().op("int4_ops"), table.status.asc().nullsLast().op("text_ops")).where(sql`(end_date IS NULL)`),
	index("idx_tlo_assignments_masterlist").using("btree", table.tloMasterlistId.asc().nullsLast().op("int4_ops")),
	index("idx_tlo_assignments_position").using("btree", table.tloPositionId.asc().nullsLast().op("text_ops")),
	index("idx_tlo_assignments_position_id").using("btree", table.positionId.asc().nullsLast().op("int4_ops")),
	index("idx_tlo_assignments_status_capacity").using("btree", table.status.asc().nullsLast().op("text_ops"), table.capacity.asc().nullsLast().op("text_ops")),
	foreignKey({
			columns: [table.tloMasterlistId],
			foreignColumns: [tloMasterlist.id],
			name: "tlo_assignments_tlo_masterlist_id_new_fkey"
		}).onDelete("cascade"),
	foreignKey({
			columns: [table.tloPositionId],
			foreignColumns: [tloItems.itemNumber],
			name: "tlo_assignments_tlo_position_id_new_fkey"
		}).onDelete("set null"),
	foreignKey({
			columns: [table.positionId],
			foreignColumns: [tloPositions.id],
			name: "tlo_assignments_position_id_fkey"
		}).onDelete("set null"),
	check("chk_tlo_assignments_status", sql`(status)::text = ANY ((ARRAY['Active'::character varying, 'Inactive'::character varying])::text[])`),
	check("chk_tlo_assignments_capacity", sql`(capacity)::text = ANY ((ARRAY['Full'::character varying, 'OIC'::character varying, 'Concurrent'::character varying])::text[])`),
]);

export const tloItems = pgTable("tlo_items", {
	itemNumber: varchar("item_number", { length: 100 }).primaryKey().notNull(),
	positionTitle: varchar("position_title", { length: 255 }).notNull(),
	salaryGrade: varchar("salary_grade", { length: 20 }),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow(),
	updatedAt: timestamp("updated_at", { withTimezone: true, mode: 'string' }).defaultNow(),
});
