-- =========================================================================================
-- Migration: 20260917_047_create_tlo_positions_and_extend_assignments.sql
-- Description:
--   1. Creates the master table 'public.tlo_positions' with canonical DepEd positions.
--   2. Populates tlo_positions with verified canonical positions inventory (598 items).
--   3. Synchronizes sequence tlo_positions_id_seq.
--   4. Extends 'public.tlo_assignments' with foreign keys 'position_id', 'tlo_masterlist_id',
--      'capacity', and 'tlo_position_id' for position assignments management.
--   5. Backfills tlo_assignments.tlo_masterlist_id from tlo_masterlist using tloid matching.
--   6. Creates performance indexes on all relational columns.
--
-- Safety & Rollback:
--   - Fully wrapped in a transaction block (BEGIN / COMMIT).
--   - Safe idempotent execution with IF NOT EXISTS checks.
--   - Preserves all existing assignment and demographic data.
--   - Rollback instructions provided at the end of this file.
-- =========================================================================================

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. Create tlo_positions Master Table
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tlo_positions (
    id SERIAL PRIMARY KEY,
    position_title VARCHAR(150) NOT NULL,
    position_code VARCHAR(100) NULL,
    salary_grade VARCHAR(20) NULL,
    region VARCHAR(255) NULL,
    division VARCHAR(255) NULL,
    bureau VARCHAR(255) NULL,
    description TEXT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes on tlo_positions
CREATE INDEX IF NOT EXISTS idx_tlo_positions_title ON public.tlo_positions USING btree (position_title);
CREATE INDEX IF NOT EXISTS idx_tlo_positions_code ON public.tlo_positions USING btree (position_code);
CREATE INDEX IF NOT EXISTS idx_tlo_positions_region ON public.tlo_positions USING btree (region);
CREATE INDEX IF NOT EXISTS idx_tlo_positions_division ON public.tlo_positions USING btree (division);
CREATE INDEX IF NOT EXISTS idx_tlo_positions_bureau ON public.tlo_positions USING btree (bureau);

COMMENT ON TABLE public.tlo_positions IS 'Master inventory of official third level positions, stations, and salary grades';

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. Populate tlo_positions Canonical Inventory
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO public.tlo_positions (id, position_title, position_code, salary_grade, region, division, bureau, description)
VALUES
    (1, 'Secretary', 'SEC', '31', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Department of Education', NULL),
    (2, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (HoPE, Senior Personnel Oversight and Government Relations)', NULL),
    (3, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (4, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Administration', NULL),
    (5, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Legal and Legislative Affairs', NULL),
    (6, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Strategic Management', NULL),
    (7, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Government Relations', NULL),
    (8, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Learning Systems', NULL),
    (9, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Support to Implementation of Public-Private Partnerships', NULL),
    (10, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Operations', NULL),
    (11, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary and Chief of Staff', NULL),
    (12, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Human Resource and Organizational Development, and Infrastructure', NULL),
    (13, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Finance and Procurement Oversight', NULL),
    (14, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Information and Communication Technology Service', NULL),
    (15, 'Undersecretary', 'USEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Learning Systems', NULL),
    (16, 'Undersecretary', 'USEC', '30', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Information and Communication Technology Service', NULL),
    (17, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Learning Systems', NULL),
    (18, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Learning Systems (ECCD and LCC)', NULL),
    (19, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Operations', NULL),
    (20, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Education Facilities', NULL),
    (21, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (22, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (23, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (24, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (25, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (26, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (27, 'Assistant Secretary', 'ASEC', '29', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (28, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Administrative Service', NULL),
    (29, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Alternative Education (BAE)', NULL),
    (30, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Education Assessment (BEA)', NULL),
    (31, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Curriculum Development (BCD)', NULL),
    (32, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learning Delivery (BLD)', NULL),
    (33, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learning Resources (BLR)', NULL),
    (34, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'National Educators Academy of the Philippines (NEAP)', NULL),
    (35, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Finance Service', NULL),
    (36, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Project Management Service (PMS)', NULL),
    (37, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learner Support Services (BLSS)', NULL),
    (38, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Disaster Risk Reduction and Management Service (DRRMS)', NULL),
    (39, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Human Resource and Organizational Development (BHROD)', NULL),
    (40, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Legal Service', NULL),
    (41, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Procurement Management Service', NULL),
    (42, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'External Partnership Service (EPS)', NULL),
    (43, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Information and Communication Technology Service (ICTS)', NULL),
    (44, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Internal Audit Service (IAS)', NULL),
    (45, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Public Affairs Service (PAS)', NULL),
    (46, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Policy and Planning Service', NULL),
    (47, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (48, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (49, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (50, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (51, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (52, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (53, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (54, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (55, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (56, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (57, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (58, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (59, 'Director IV', 'DIR4', '28', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary', NULL),
    (60, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Curriculum Development (BCD)', NULL),
    (61, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learning Delivery (BLD)', NULL),
    (62, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learning Resources (BLR)', NULL),
    (63, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learning Resources (BLR)-Cebu', NULL),
    (64, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Alternative Education (BAE)', NULL),
    (65, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Education Assessment (BEA)', NULL),
    (66, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'National Educators Academy of the Philippines (NEAP)', NULL),
    (67, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Learner Support Services (BLSS)', NULL),
    (68, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Human Resource and Organizational Development (BHROD)', NULL),
    (69, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Bureau of Human Resource and Organizational Development (BHROD)', NULL),
    (70, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (71, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (72, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (73, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (74, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (75, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (76, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (77, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (78, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (79, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (80, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (81, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (82, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (83, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (84, 'Director III', 'DIR3', '27', 'CENTRAL OFFICE', 'CENTRAL OFFICE', 'Office of the Secretary (CT)', NULL),
    (85, 'Regional Director', 'RD', '28', 'REGION I', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (86, 'Assistant Regional Director', 'ARD', '27', 'REGION I', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (87, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'ILOCOS NORTE', NULL, NULL),
    (88, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'ILOCOS NORTE', NULL, NULL),
    (89, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'ILOCOS SUR', NULL, NULL),
    (90, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'ILOCOS SUR', NULL, NULL),
    (91, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'LA UNION', NULL, NULL),
    (92, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'LA UNION', NULL, NULL),
    (93, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'PANGASINAN I', NULL, NULL),
    (94, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'PANGASINAN I', NULL, NULL),
    (95, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'PANGASINAN I', NULL, NULL),
    (96, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'PANGASINAN II', NULL, NULL),
    (97, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'PANGASINAN II', NULL, NULL),
    (98, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'PANGASINAN II', NULL, NULL),
    (99, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'ALAMINOS CITY', NULL, NULL),
    (100, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'ALAMINOS CITY', NULL, NULL),
    (101, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'BATAC CITY', NULL, NULL),
    (102, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'BATAC CITY', NULL, NULL),
    (103, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'CANDON CITY', NULL, NULL),
    (104, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'CANDON CITY', NULL, NULL),
    (105, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'DAGUPAN CITY', NULL, NULL),
    (106, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'DAGUPAN CITY', NULL, NULL),
    (107, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'LAOAG CITY', NULL, NULL),
    (108, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'LAOAG CITY', NULL, NULL),
    (109, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'SAN CARLOS CITY', NULL, NULL),
    (110, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'SAN CARLOS CITY', NULL, NULL),
    (111, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'SAN FERNANDO CITY', NULL, NULL),
    (112, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'SAN FERNANDO CITY', NULL, NULL),
    (113, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'URDANETA CITY', NULL, NULL),
    (114, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'URDANETA CITY', NULL, NULL),
    (115, 'Schools Division Superintendent', 'SDS', '26', 'REGION I', 'VIGAN CITY', NULL, NULL),
    (116, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION I', 'VIGAN CITY', NULL, NULL),
    (117, 'Regional Director', 'RD', '28', 'REGION II', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (118, 'Assistant Regional Director', 'ARD', '27', 'REGION II', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (119, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'BATANES', NULL, NULL),
    (120, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'BATANES', NULL, NULL),
    (121, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'CAGAYAN', NULL, NULL),
    (122, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'CAGAYAN', NULL, NULL),
    (123, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'CAGAYAN', NULL, NULL),
    (124, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'ISABELA', NULL, NULL),
    (125, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'ISABELA', NULL, NULL),
    (126, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'ISABELA', NULL, NULL),
    (127, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'NUEVA VIZCAYA', NULL, NULL),
    (128, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'NUEVA VIZCAYA', NULL, NULL),
    (129, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'QUIRINO', NULL, NULL),
    (130, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'QUIRINO', NULL, NULL),
    (131, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'CAUAYAN CITY', NULL, NULL),
    (132, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'CAUAYAN CITY', NULL, NULL),
    (133, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'ILAGAN CITY', NULL, NULL),
    (134, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'ILAGAN CITY', NULL, NULL),
    (135, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'SANTIAGO CITY', NULL, NULL),
    (136, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'SANTIAGO CITY', NULL, NULL),
    (137, 'Schools Division Superintendent', 'SDS', '26', 'REGION II', 'TUGUEGARAO CITY', NULL, NULL),
    (138, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION II', 'TUGUEGARAO CITY', NULL, NULL),
    (139, 'Regional Director', 'RD', '28', 'REGION III', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (140, 'Assistant Regional Director', 'ARD', '27', 'REGION III', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (141, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'AURORA', NULL, NULL),
    (142, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'AURORA', NULL, NULL),
    (143, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'BATAAN', NULL, NULL),
    (144, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'BATAAN', NULL, NULL),
    (145, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'BULACAN', NULL, NULL),
    (146, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'BULACAN', NULL, NULL),
    (147, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'BULACAN', NULL, NULL),
    (148, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'NUEVA ECIJA', NULL, NULL),
    (149, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'NUEVA ECIJA', NULL, NULL),
    (150, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'NUEVA ECIJA', NULL, NULL),
    (151, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'PAMPANGA', NULL, NULL),
    (152, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'PAMPANGA', NULL, NULL),
    (153, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'PAMPANGA', NULL, NULL),
    (154, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'TARLAC', NULL, NULL),
    (155, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'TARLAC', NULL, NULL),
    (156, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'TARLAC', NULL, NULL),
    (157, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'ZAMBALES', NULL, NULL),
    (158, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'ZAMBALES', NULL, NULL),
    (159, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'ANGELES CITY', NULL, NULL),
    (160, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'ANGELES CITY', NULL, NULL),
    (161, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'BALANGA CITY', NULL, NULL),
    (162, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'BALANGA CITY', NULL, NULL),
    (163, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'CABANATUAN CITY', NULL, NULL),
    (164, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'CABANATUAN CITY', NULL, NULL),
    (165, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'GAPAN CITY', NULL, NULL),
    (166, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'GAPAN CITY', NULL, NULL),
    (167, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'MABALACAT CITY', NULL, NULL),
    (168, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'MABALACAT CITY', NULL, NULL),
    (169, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'MALOLOS CITY', NULL, NULL),
    (170, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'MALOLOS CITY', NULL, NULL),
    (171, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'MEYCAUAYAN CITY', NULL, NULL),
    (172, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'MEYCAUAYAN CITY', NULL, NULL),
    (173, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'OLONGAPO CITY', NULL, NULL),
    (174, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'OLONGAPO CITY', NULL, NULL),
    (175, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'SAN FERNANDO CITY', NULL, NULL),
    (176, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'SAN FERNANDO CITY', NULL, NULL),
    (177, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'SAN JOSE CITY', NULL, NULL),
    (178, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'SAN JOSE CITY', NULL, NULL),
    (179, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'SAN JOSE DEL MONTE CITY', NULL, NULL),
    (180, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'SAN JOSE DEL MONTE CITY', NULL, NULL),
    (181, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'SCIENCE CITY OF MUNOZ', NULL, NULL),
    (182, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'SCIENCE CITY OF MUNOZ', NULL, NULL),
    (183, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'TARLAC CITY', NULL, NULL),
    (184, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'TARLAC CITY', NULL, NULL),
    (185, 'Schools Division Superintendent', 'SDS', '26', 'REGION III', 'BALIWAG CITY', NULL, NULL),
    (186, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION III', 'BALIWAG CITY', NULL, NULL),
    (187, 'Regional Director', 'RD', '28', 'REGION IV-A', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (188, 'Assistant Regional Director', 'ARD', '27', 'REGION IV-A', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (189, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'BATANGAS', NULL, NULL),
    (190, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'BATANGAS', NULL, NULL),
    (191, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'BATANGAS', NULL, NULL),
    (192, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'CAVITE', NULL, NULL),
    (193, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CAVITE', NULL, NULL),
    (194, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CAVITE', NULL, NULL),
    (195, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'LAGUNA', NULL, NULL),
    (196, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'LAGUNA', NULL, NULL),
    (197, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'LAGUNA', NULL, NULL),
    (198, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'QUEZON', NULL, NULL),
    (199, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'QUEZON', NULL, NULL),
    (200, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'QUEZON', NULL, NULL),
    (201, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'QUEZON', NULL, NULL),
    (202, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'RIZAL', NULL, NULL),
    (203, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'RIZAL', NULL, NULL),
    (204, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'RIZAL', NULL, NULL),
    (205, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'ANTIPOLO CITY', NULL, NULL),
    (206, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'ANTIPOLO CITY', NULL, NULL),
    (207, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'BACOOR CITY', NULL, NULL),
    (208, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'BACOOR CITY', NULL, NULL),
    (209, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'BATANGAS CITY', NULL, NULL),
    (210, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'BATANGAS CITY', NULL, NULL),
    (211, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'BIÃAN CITY', NULL, NULL),
    (212, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'BIÃAN CITY', NULL, NULL),
    (213, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'CABUYAO CITY', NULL, NULL),
    (214, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CABUYAO CITY', NULL, NULL),
    (215, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'CALACA CITY', NULL, NULL),
    (216, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CALACA CITY', NULL, NULL),
    (217, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'CALAMBA CITY', NULL, NULL),
    (218, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CALAMBA CITY', NULL, NULL),
    (219, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'CAVITE CITY', NULL, NULL),
    (220, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CAVITE CITY', NULL, NULL),
    (221, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'CARMONA CITY', NULL, NULL),
    (222, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'CARMONA CITY', NULL, NULL),
    (223, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'DASMARIÃAS CITY', NULL, NULL),
    (224, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'DASMARIÃAS CITY', NULL, NULL),
    (225, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'IMUS CITY', NULL, NULL),
    (226, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'IMUS CITY', NULL, NULL),
    (227, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'LIPA CITY', NULL, NULL),
    (228, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'LIPA CITY', NULL, NULL),
    (229, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'LUCENA CITY', NULL, NULL),
    (230, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'LUCENA CITY', NULL, NULL),
    (231, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'SAN PABLO CITY', NULL, NULL),
    (232, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'SAN PABLO CITY', NULL, NULL),
    (233, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'STA. ROSA CITY', NULL, NULL),
    (234, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'STA. ROSA CITY', NULL, NULL),
    (235, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'TANAUAN CITY', NULL, NULL),
    (236, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'TANAUAN CITY', NULL, NULL),
    (237, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'TAYABAS CITY', NULL, NULL),
    (238, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'TAYABAS CITY', NULL, NULL),
    (239, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'GENERAL TRIAS CITY', NULL, NULL),
    (240, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'GENERAL TRIAS CITY', NULL, NULL),
    (241, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'SAN PEDRO CITY', NULL, NULL),
    (242, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'SAN PEDRO CITY', NULL, NULL),
    (243, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-A', 'STO. TOMAS CITY', NULL, NULL),
    (244, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-A', 'STO. TOMAS CITY', NULL, NULL),
    (245, 'Regional Director', 'RD', '28', 'REGION IV-B', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (246, 'Assistant Regional Director', 'ARD', '27', 'REGION IV-B', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (247, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'MARINDUQUE', NULL, NULL),
    (248, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'MARINDUQUE', NULL, NULL),
    (249, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'OCCIDENTAL MINDORO', NULL, NULL),
    (250, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'OCCIDENTAL MINDORO', NULL, NULL),
    (251, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'ORIENTAL MINDORO', NULL, NULL),
    (252, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'ORIENTAL MINDORO', NULL, NULL),
    (253, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'PALAWAN', NULL, NULL),
    (254, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'PALAWAN', NULL, NULL),
    (255, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'PALAWAN', NULL, NULL),
    (256, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'ROMBLON', NULL, NULL),
    (257, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'ROMBLON', NULL, NULL),
    (258, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'CALAPAN CITY', NULL, NULL),
    (259, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'CALAPAN CITY', NULL, NULL),
    (260, 'Schools Division Superintendent', 'SDS', '26', 'REGION IV-B', 'PUERTO PRINCESA CITY', NULL, NULL),
    (261, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IV-B', 'PUERTO PRINCESA CITY', NULL, NULL),
    (262, 'Regional Director', 'RD', '28', 'REGION V', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (263, 'Assistant Regional Director', 'ARD', '27', 'REGION V', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (264, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'ALBAY', NULL, NULL),
    (265, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'ALBAY', NULL, NULL),
    (266, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'ALBAY', NULL, NULL),
    (267, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'CAMARINES NORTE', NULL, NULL),
    (268, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'CAMARINES NORTE', NULL, NULL),
    (269, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'CAMARINES SUR', NULL, NULL),
    (270, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'CAMARINES SUR', NULL, NULL),
    (271, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'CAMARINES SUR', NULL, NULL),
    (272, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'CAMARINES SUR', NULL, NULL),
    (273, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'CATANDUANES', NULL, NULL),
    (274, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'CATANDUANES', NULL, NULL),
    (275, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'MASBATE', NULL, NULL),
    (276, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'MASBATE', NULL, NULL),
    (277, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'MASBATE', NULL, NULL),
    (278, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'SORSOGON', NULL, NULL),
    (279, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'SORSOGON', NULL, NULL),
    (280, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'IRIGA CITY', NULL, NULL),
    (281, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'IRIGA CITY', NULL, NULL),
    (282, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'LEGAZPI CITY', NULL, NULL),
    (283, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'LEGAZPI CITY', NULL, NULL),
    (284, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'LIGAO CITY', NULL, NULL),
    (285, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'LIGAO CITY', NULL, NULL),
    (286, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'MASBATE CITY', NULL, NULL),
    (287, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'MASBATE CITY', NULL, NULL),
    (288, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'NAGA CITY', NULL, NULL),
    (289, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'NAGA CITY', NULL, NULL),
    (290, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'SORSOGON CITY', NULL, NULL),
    (291, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'SORSOGON CITY', NULL, NULL),
    (292, 'Schools Division Superintendent', 'SDS', '26', 'REGION V', 'TABACO CITY', NULL, NULL),
    (293, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION V', 'TABACO CITY', NULL, NULL),
    (294, 'Regional Director', 'RD', '28', 'REGION VI', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (295, 'Assistant Regional Director', 'ARD', '27', 'REGION VI', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (296, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'AKLAN', NULL, NULL),
    (297, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'AKLAN', NULL, NULL),
    (298, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'ANTIQUE', NULL, NULL),
    (299, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ANTIQUE', NULL, NULL),
    (300, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'CAPIZ', NULL, NULL),
    (301, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'CAPIZ', NULL, NULL),
    (302, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'GUIMARAS', NULL, NULL),
    (303, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'GUIMARAS', NULL, NULL),
    (304, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'ILOILO', NULL, NULL),
    (305, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ILOILO', NULL, NULL),
    (306, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ILOILO', NULL, NULL),
    (307, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ILOILO', NULL, NULL),
    (308, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'ILOILO CITY', NULL, NULL),
    (309, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ILOILO CITY', NULL, NULL),
    (310, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'PASSI CITY', NULL, NULL),
    (311, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'PASSI CITY', NULL, NULL),
    (312, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'ROXAS CITY', NULL, NULL),
    (313, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ROXAS CITY', NULL, NULL),
    (314, 'Regional Director', 'RD', '28', 'REGION VI', 'NEGROS ISLAND REGION', NULL, NULL),
    (315, 'Assistant Regional Director', 'ARD', '27', 'REGION VI', 'NEGROS ISLAND REGION', NULL, NULL),
    (316, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'NEGROS OCCIDENTAL', NULL, NULL),
    (317, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'NEGROS OCCIDENTAL', NULL, NULL),
    (318, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'NEGROS OCCIDENTAL', NULL, NULL),
    (319, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'NEGROS ORIENTAL', NULL, NULL),
    (320, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'NEGROS ORIENTAL', NULL, NULL),
    (321, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'NEGROS ORIENTAL', NULL, NULL),
    (322, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'SIQUIJOR', NULL, NULL),
    (323, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'SIQUIJOR', NULL, NULL),
    (324, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'BACOLOD CITY', NULL, NULL),
    (325, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'BACOLOD CITY', NULL, NULL),
    (326, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'BAGO CITY', NULL, NULL),
    (327, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'BAGO CITY', NULL, NULL),
    (328, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'BAIS CITY', NULL, NULL),
    (329, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'BAIS CITY', NULL, NULL),
    (330, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'BAYAWAN CITY', NULL, NULL),
    (331, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'BAYAWAN CITY', NULL, NULL),
    (332, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'CADIZ CITY', NULL, NULL),
    (333, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'CADIZ CITY', NULL, NULL),
    (334, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'CANLAON CITY', NULL, NULL),
    (335, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'CANLAON CITY', NULL, NULL),
    (336, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'DUMAGUETE CITY', NULL, NULL),
    (337, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'DUMAGUETE CITY', NULL, NULL),
    (338, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'ESCALANTE CITY', NULL, NULL),
    (339, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'ESCALANTE CITY', NULL, NULL),
    (340, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'GUIHULNGAN CITY', NULL, NULL),
    (341, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'GUIHULNGAN CITY', NULL, NULL),
    (342, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'HIMAMAYLAN CITY', NULL, NULL),
    (343, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'HIMAMAYLAN CITY', NULL, NULL),
    (344, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'KABANKALAN CITY', NULL, NULL),
    (345, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'KABANKALAN CITY', NULL, NULL),
    (346, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'LA CARLOTA CITY', NULL, NULL),
    (347, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'LA CARLOTA CITY', NULL, NULL),
    (348, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'SAGAY CITY', NULL, NULL),
    (349, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VI', 'SAGAY CITY', NULL, NULL),
    (350, 'Schools Division Superintendent', 'SDS', '26', 'REGION VI', 'SAN CARLOS CITY', NULL, NULL),
    (351, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VI', 'SAN CARLOS CITY', NULL, NULL),
    (352, 'Schools Division Superintendent', 'SDS', '25', 'REGION VI', 'SILAY CITY', NULL, NULL),
    (353, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VI', 'SILAY CITY', NULL, NULL),
    (354, 'Schools Division Superintendent', 'SDS', '25', 'REGION VI', 'SIPALAY CITY', NULL, NULL),
    (355, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VI', 'SIPALAY CITY', NULL, NULL),
    (356, 'Schools Division Superintendent', 'SDS', '25', 'REGION VI', 'TALISAY CITY', NULL, NULL),
    (357, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VI', 'TALISAY CITY', NULL, NULL),
    (358, 'Schools Division Superintendent', 'SDS', '25', 'REGION VI', 'TANJAY CITY', NULL, NULL),
    (359, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VI', 'TANJAY CITY', NULL, NULL),
    (360, 'Schools Division Superintendent', 'SDS', '25', 'REGION VI', 'VICTORIAS CITY', NULL, NULL),
    (361, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION VI', 'VICTORIAS CITY', NULL, NULL),
    (362, 'Regional Director', 'RD', '27', 'REGION VII', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (363, 'Assistant Regional Director', 'ARD', '26', 'REGION VII', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (364, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'BOHOL', NULL, NULL),
    (365, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VII', 'BOHOL', NULL, NULL),
    (366, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'BOHOL', NULL, NULL),
    (367, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'CEBU', NULL, NULL),
    (368, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VII', 'CEBU', NULL, NULL),
    (369, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VII', 'CEBU', NULL, NULL),
    (370, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'CEBU', NULL, NULL),
    (371, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'BOGO CITY', NULL, NULL),
    (372, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'BOGO CITY', NULL, NULL),
    (373, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'CARCAR CITY', NULL, NULL),
    (374, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'CARCAR CITY', NULL, NULL),
    (375, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'CEBU CITY', NULL, NULL),
    (376, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'CEBU CITY', NULL, NULL),
    (377, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'DANAO CITY', NULL, NULL),
    (378, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'DANAO CITY', NULL, NULL),
    (379, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'LAPU-LAPU CITY', NULL, NULL),
    (380, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'LAPU-LAPU CITY', NULL, NULL),
    (381, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'MANDAUE CITY', NULL, NULL),
    (382, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'MANDAUE CITY', NULL, NULL),
    (383, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'NAGA CITY', NULL, NULL),
    (384, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'NAGA CITY', NULL, NULL),
    (385, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'TAGBILARAN CITY', NULL, NULL),
    (386, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'TAGBILARAN CITY', NULL, NULL),
    (387, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'TALISAY CITY', NULL, NULL),
    (388, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VII', 'TALISAY CITY', NULL, NULL),
    (389, 'Schools Division Superintendent', 'SDS', '25', 'REGION VII', 'TOLEDO CITY', NULL, NULL),
    (390, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION VII', 'TOLEDO CITY', NULL, NULL),
    (391, 'Regional Director', 'RD', '27', 'REGION VIII', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (392, 'Assistant Regional Director', 'ARD', '26', 'REGION VIII', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (393, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'BILIRAN', NULL, NULL),
    (394, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'BILIRAN', NULL, NULL),
    (395, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'EASTERN SAMAR', NULL, NULL),
    (396, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'EASTERN SAMAR', NULL, NULL),
    (397, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'LEYTE', NULL, NULL),
    (398, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION VIII', 'LEYTE', NULL, NULL),
    (399, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'LEYTE', NULL, NULL),
    (400, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'NORTHERN SAMAR', NULL, NULL),
    (401, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'NORTHERN SAMAR', NULL, NULL),
    (402, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'SAMAR', NULL, NULL),
    (403, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'SAMAR', NULL, NULL),
    (404, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'SOUTHERN LEYTE', NULL, NULL),
    (405, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'SOUTHERN LEYTE', NULL, NULL),
    (406, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'BAYBAY CITY', NULL, NULL),
    (407, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'BAYBAY CITY', NULL, NULL),
    (408, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'BORONGAN CITY', NULL, NULL),
    (409, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'BORONGAN CITY', NULL, NULL),
    (410, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'CALBAYOG CITY', NULL, NULL),
    (411, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'CALBAYOG CITY', NULL, NULL),
    (412, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'CATBALOGAN CITY', NULL, NULL),
    (413, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'CATBALOGAN CITY', NULL, NULL),
    (414, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'MAASIN CITY', NULL, NULL),
    (415, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'MAASIN CITY', NULL, NULL),
    (416, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'ORMOC CITY', NULL, NULL),
    (417, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION VIII', 'ORMOC CITY', NULL, NULL),
    (418, 'Schools Division Superintendent', 'SDS', '25', 'REGION VIII', 'TACLOBAN CITY', NULL, NULL),
    (419, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION VIII', 'TACLOBAN CITY', NULL, NULL),
    (420, 'Regional Director', 'RD', '27', 'REGION IX', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (421, 'Assistant Regional Director', 'ARD', '26', 'REGION IX', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (422, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'SULU', NULL, NULL),
    (423, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'SULU', NULL, NULL),
    (424, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'ZAMBOANGA DEL NORTE', NULL, NULL),
    (425, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IX', 'ZAMBOANGA DEL NORTE', NULL, NULL),
    (426, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'ZAMBOANGA DEL NORTE', NULL, NULL),
    (427, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'ZAMBOANGA DEL SUR', NULL, NULL),
    (428, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION IX', 'ZAMBOANGA DEL SUR', NULL, NULL),
    (429, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'ZAMBOANGA DEL SUR', NULL, NULL),
    (430, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'ZAMBOANGA SIBUGAY', NULL, NULL),
    (431, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'ZAMBOANGA SIBUGAY', NULL, NULL),
    (432, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'DAPITAN CITY', NULL, NULL),
    (433, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'DAPITAN CITY', NULL, NULL),
    (434, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'DIPOLOG CITY', NULL, NULL),
    (435, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'DIPOLOG CITY', NULL, NULL),
    (436, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'ISABELA CITY', NULL, NULL),
    (437, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'ISABELA CITY', NULL, NULL),
    (438, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'PAGADIAN CITY', NULL, NULL),
    (439, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION IX', 'PAGADIAN CITY', NULL, NULL),
    (440, 'Schools Division Superintendent', 'SDS', '25', 'REGION IX', 'ZAMBOANGA CITY', NULL, NULL),
    (441, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION IX', 'ZAMBOANGA CITY', NULL, NULL),
    (442, 'Regional Director', 'RD', '27', 'REGION X', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (443, 'Assistant Regional Director', 'ARD', '26', 'REGION X', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (444, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'BUKIDNON', NULL, NULL),
    (445, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION X', 'BUKIDNON', NULL, NULL),
    (446, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'BUKIDNON', NULL, NULL),
    (447, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'CAMIGUIN', NULL, NULL),
    (448, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'CAMIGUIN', NULL, NULL),
    (449, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'LANAO DEL NORTE', NULL, NULL),
    (450, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'LANAO DEL NORTE', NULL, NULL),
    (451, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'MISAMIS OCCIDENTAL', NULL, NULL),
    (452, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'MISAMIS OCCIDENTAL', NULL, NULL),
    (453, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'MISAMIS ORIENTAL', NULL, NULL),
    (454, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'MISAMIS ORIENTAL', NULL, NULL),
    (455, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'CAGAYAN DE ORO CITY', NULL, NULL),
    (456, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'CAGAYAN DE ORO CITY', NULL, NULL),
    (457, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'EL SALVADOR CITY', NULL, NULL),
    (458, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'EL SALVADOR CITY', NULL, NULL),
    (459, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'GINGOOG CITY', NULL, NULL),
    (460, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'GINGOOG CITY', NULL, NULL),
    (461, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'ILIGAN CITY', NULL, NULL),
    (462, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'ILIGAN CITY', NULL, NULL),
    (463, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'MALAYBALAY CITY', NULL, NULL),
    (464, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'MALAYBALAY CITY', NULL, NULL),
    (465, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'OROQUIETA CITY', NULL, NULL),
    (466, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'OROQUIETA CITY', NULL, NULL),
    (467, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'OZAMIS CITY', NULL, NULL),
    (468, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'OZAMIS CITY', NULL, NULL),
    (469, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'TANGUB CITY', NULL, NULL),
    (470, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION X', 'TANGUB CITY', NULL, NULL),
    (471, 'Schools Division Superintendent', 'SDS', '25', 'REGION X', 'VALENCIA CITY', NULL, NULL),
    (472, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION X', 'VALENCIA CITY', NULL, NULL),
    (473, 'Regional Director', 'RD', '27', 'REGION XI', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (474, 'Assistant Regional Director', 'ARD', '26', 'REGION XI', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (475, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DAVAO DE ORO', NULL, NULL),
    (476, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DAVAO DE ORO', NULL, NULL),
    (477, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DAVAO DEL NORTE', NULL, NULL),
    (478, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DAVAO DEL NORTE', NULL, NULL),
    (479, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DAVAO DEL SUR', NULL, NULL),
    (480, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DAVAO DEL SUR', NULL, NULL),
    (481, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DAVAO OCCIDENTAL', NULL, NULL),
    (482, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DAVAO OCCIDENTAL', NULL, NULL),
    (483, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DAVAO ORIENTAL', NULL, NULL),
    (484, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DAVAO ORIENTAL', NULL, NULL),
    (485, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DAVAO CITY', NULL, NULL),
    (486, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION XI', 'DAVAO CITY', NULL, NULL),
    (487, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DAVAO CITY', NULL, NULL),
    (488, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'DIGOS CITY', NULL, NULL),
    (489, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'DIGOS CITY', NULL, NULL),
    (490, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'MATI CITY', NULL, NULL),
    (491, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'MATI CITY', NULL, NULL),
    (492, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'PANABO CITY', NULL, NULL),
    (493, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'PANABO CITY', NULL, NULL),
    (494, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'SAMAL CITY', NULL, NULL),
    (495, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XI', 'SAMAL CITY', NULL, NULL),
    (496, 'Schools Division Superintendent', 'SDS', '25', 'REGION XI', 'TAGUM CITY', NULL, NULL),
    (497, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION XI', 'TAGUM CITY', NULL, NULL),
    (498, 'Regional Director', 'RD', '27', 'REGION XII', 'REGION  XII', NULL, NULL),
    (499, 'Assistant Regional Director', 'ARD', '26', 'REGION XII', 'REGION  XII', NULL, NULL),
    (500, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'COTABATO', NULL, NULL),
    (501, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'REGION XII', 'COTABATO', NULL, NULL),
    (502, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'COTABATO', NULL, NULL),
    (503, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'SARANGGANI', NULL, NULL),
    (504, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'SARANGGANI', NULL, NULL),
    (505, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'SOUTH COTABATO', NULL, NULL),
    (506, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'SOUTH COTABATO', NULL, NULL),
    (507, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'SULTAN KUDARAT', NULL, NULL),
    (508, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'SULTAN KUDARAT', NULL, NULL),
    (509, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'GENERAL SANTOS CITY', NULL, NULL),
    (510, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'GENERAL SANTOS CITY', NULL, NULL),
    (511, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'KIDAPAWAN CITY', NULL, NULL),
    (512, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'KIDAPAWAN CITY', NULL, NULL),
    (513, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'KORONADAL CITY', NULL, NULL),
    (514, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XII', 'KORONADAL CITY', NULL, NULL),
    (515, 'Schools Division Superintendent', 'SDS', '25', 'REGION XII', 'TACURONG CITY', NULL, NULL),
    (516, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION XII', 'TACURONG CITY', NULL, NULL),
    (517, 'Regional Director', 'RD', '27', 'REGION XIII', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (518, 'Assistant Regional Director', 'ARD', '26', 'REGION XIII', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (519, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'AGUSAN DEL NORTE', NULL, NULL),
    (520, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'AGUSAN DEL NORTE', NULL, NULL),
    (521, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'AGUSAN DEL SUR', NULL, NULL),
    (522, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'AGUSAN DEL SUR', NULL, NULL),
    (523, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'DINAGAT ISLANDS', NULL, NULL),
    (524, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'DINAGAT ISLANDS', NULL, NULL),
    (525, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'SURIGAO DEL NORTE', NULL, NULL),
    (526, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'SURIGAO DEL NORTE', NULL, NULL),
    (527, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'SURIGAO DEL SUR', NULL, NULL),
    (528, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'SURIGAO DEL SUR', NULL, NULL),
    (529, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'BAYUGAN CITY', NULL, NULL),
    (530, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'BAYUGAN CITY', NULL, NULL),
    (531, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'BISLIG CITY', NULL, NULL),
    (532, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'BISLIG CITY', NULL, NULL),
    (533, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'BUTUAN CITY', NULL, NULL),
    (534, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'BUTUAN CITY', NULL, NULL),
    (535, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'CABADBARAN CITY', NULL, NULL),
    (536, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'CABADBARAN CITY', NULL, NULL),
    (537, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'SIARGAO', NULL, NULL),
    (538, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'SIARGAO', NULL, NULL),
    (539, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'SURIGAO CITY', NULL, NULL),
    (540, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'REGION XIII', 'SURIGAO CITY', NULL, NULL),
    (541, 'Schools Division Superintendent', 'SDS', '25', 'REGION XIII', 'TANDAG CITY', NULL, NULL),
    (542, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'REGION XIII', 'TANDAG CITY', NULL, NULL),
    (543, 'Regional Director', 'RD', '27', 'CORDILLERA ADMINISTRATIVE REGION', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (544, 'Assistant Regional Director', 'ARD', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (545, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'ABRA', NULL, NULL),
    (546, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'ABRA', NULL, NULL),
    (547, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'APAYAO', NULL, NULL),
    (548, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'APAYAO', NULL, NULL),
    (549, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'BENGUET', NULL, NULL),
    (550, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'BENGUET', NULL, NULL),
    (551, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'IFUGAO', NULL, NULL),
    (552, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'IFUGAO', NULL, NULL),
    (553, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'KALINGA', NULL, NULL),
    (554, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'KALINGA', NULL, NULL),
    (555, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'MT. PROVINCE', NULL, NULL),
    (556, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'MT. PROVINCE', NULL, NULL),
    (557, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'BAGUIO CITY', NULL, NULL),
    (558, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'CORDILLERA ADMINISTRATIVE REGION', 'BAGUIO CITY', NULL, NULL),
    (559, 'Schools Division Superintendent', 'SDS', '25', 'CORDILLERA ADMINISTRATIVE REGION', 'TABUK CITY', NULL, NULL),
    (560, 'Assistant Schools Division Superintendent', 'ASDS', '28', 'CORDILLERA ADMINISTRATIVE REGION', 'TABUK CITY', NULL, NULL),
    (561, 'Regional Director', 'RD', '27', 'NATIONAL CAPITAL REGION', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (562, 'Assistant Regional Director', 'ARD', '26', 'NATIONAL CAPITAL REGION', 'REGIONAL OFFICE-PROPER', NULL, NULL),
    (563, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'CALOOCAN CITY', NULL, NULL),
    (564, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'NATIONAL CAPITAL REGION', 'CALOOCAN CITY', NULL, NULL),
    (565, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'CALOOCAN CITY', NULL, NULL),
    (566, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'LAS PINAS CITY', NULL, NULL),
    (567, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'LAS PINAS CITY', NULL, NULL),
    (568, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'MAKATI CITY', NULL, NULL),
    (569, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'MAKATI CITY', NULL, NULL),
    (570, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'MALABON CITY', NULL, NULL),
    (571, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'MALABON CITY', NULL, NULL),
    (572, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'MANDALUYONG CITY', NULL, NULL),
    (573, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'MANDALUYONG CITY', NULL, NULL),
    (574, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'MANILA', NULL, NULL),
    (575, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'NATIONAL CAPITAL REGION', 'MANILA', NULL, NULL),
    (576, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'MANILA', NULL, NULL),
    (577, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'MARIKINA CITY', NULL, NULL),
    (578, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'MARIKINA CITY', NULL, NULL),
    (579, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'MUNTILUPA CITY', NULL, NULL),
    (580, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'MUNTILUPA CITY', NULL, NULL),
    (581, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'NAVOTAS CITY', NULL, NULL),
    (582, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'NAVOTAS CITY', NULL, NULL),
    (583, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'PARAÃAQUE CITY', NULL, NULL),
    (584, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'PARAÃAQUE CITY', NULL, NULL),
    (585, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'PASAY CITY', NULL, NULL),
    (586, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'PASAY CITY', NULL, NULL),
    (587, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'PASIG CITY', NULL, NULL),
    (588, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'PASIG CITY', NULL, NULL),
    (589, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'QUEZON CITY', NULL, NULL),
    (590, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'NATIONAL CAPITAL REGION', 'QUEZON CITY', NULL, NULL),
    (591, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'QUEZON CITY', NULL, NULL),
    (592, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'SAN JUAN CITY', NULL, NULL),
    (593, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'SAN JUAN CITY', NULL, NULL),
    (594, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'TAGUIG CITY-PATEROS', NULL, NULL),
    (595, 'Assistant Schools Division Superintendent', 'ASDS', '26', 'NATIONAL CAPITAL REGION', 'TAGUIG CITY-PATEROS', NULL, NULL),
    (596, 'Schools Division Superintendent', 'SDS', '25', 'NATIONAL CAPITAL REGION', 'VALENZUELA CITY', NULL, NULL),
    (597, 'Assistant Schools Division Superintendent', 'ASDS', '25', 'NATIONAL CAPITAL REGION', 'VALENZUELA CITY', NULL, NULL),
    (600, 'Director II', NULL, '24', 'CENTRAL OFFICE', NULL, NULL, NULL)
ON CONFLICT (id) DO UPDATE SET
    position_title = EXCLUDED.position_title,
    position_code = EXCLUDED.position_code,
    salary_grade = EXCLUDED.salary_grade,
    region = EXCLUDED.region,
    division = EXCLUDED.division,
    bureau = EXCLUDED.bureau,
    description = EXCLUDED.description;

SELECT setval('public.tlo_positions_id_seq', COALESCE((SELECT MAX(id) FROM public.tlo_positions), 1));

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. Extend tlo_assignments Table
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.tlo_assignments
    ADD COLUMN IF NOT EXISTS position_id INTEGER REFERENCES public.tlo_positions(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS capacity VARCHAR(20) NOT NULL DEFAULT 'Full',
    ADD COLUMN IF NOT EXISTS tlo_masterlist_id INTEGER REFERENCES public.tlo_masterlist(id) ON DELETE SET NULL,
    ADD COLUMN IF NOT EXISTS tlo_position_id VARCHAR(255);

-- Performance and lookup indexes
CREATE INDEX IF NOT EXISTS idx_tlo_assignments_masterlist ON public.tlo_assignments(tlo_masterlist_id);
CREATE INDEX IF NOT EXISTS idx_tlo_assignments_position_id ON public.tlo_assignments(position_id);
CREATE INDEX IF NOT EXISTS idx_tlo_assignments_capacity ON public.tlo_assignments(capacity);

-- ─────────────────────────────────────────────────────────────────────────────
-- 4. Backfill Relational Links on tlo_assignments
-- ─────────────────────────────────────────────────────────────────────────────
UPDATE public.tlo_assignments a
SET tlo_masterlist_id = m.id
FROM public.tlo_masterlist m
WHERE a.tlo_masterlist_id IS NULL
  AND LOWER(TRIM(a.item_number)) = LOWER(TRIM(m.tloid));

COMMIT;

-- =========================================================================================
-- ROLLBACK INSTRUCTIONS:
-- To rollback this migration, run the following SQL block:
-- BEGIN;
-- ALTER TABLE public.tlo_assignments DROP COLUMN IF EXISTS position_id CASCADE;
-- ALTER TABLE public.tlo_assignments DROP COLUMN IF EXISTS capacity CASCADE;
-- ALTER TABLE public.tlo_assignments DROP COLUMN IF EXISTS tlo_masterlist_id CASCADE;
-- ALTER TABLE public.tlo_assignments DROP COLUMN IF EXISTS tlo_position_id CASCADE;
-- DROP TABLE IF EXISTS public.tlo_positions CASCADE;
-- COMMIT;
-- =========================================================================================
