-- Migration: 20260903_021_clean_suffix_not_applicable.sql
-- Description: Normalizes verified legacy placeholder suffix values ('Not applicable', 'NA', 'na', 'NOT APPLICABLE', 'NOT APLLICABLE')
--              in third_level_officials_profiling_application and third_level_official_masterlist to NULL.
-- Safety: Idempotent data cleanup, non-destructive to valid suffix records.
--
-- Rollback Instructions:
-- The legacy placeholder strings were non-data placeholders generated by prompt instructions.
-- If rollback is strictly needed, the original 3 staging records can be restored with:
--   UPDATE third_level_officials_profiling_application SET suffix = 'NA' WHERE app_tloid = 'TLO-2026-0006';
--   UPDATE third_level_officials_profiling_application SET suffix = 'Not applicable' WHERE app_tloid = 'TLO-2026-0005';
--   UPDATE third_level_officials_profiling_application SET suffix = 'na' WHERE app_tloid = 'TLO-2026-0007';

BEGIN;

UPDATE third_level_officials_profiling_application
SET suffix = NULL,
    updated_at = NOW()
WHERE suffix IS NOT NULL
  AND TRIM(LOWER(suffix)) IN ('not applicable', 'not apllicable', 'na');

UPDATE third_level_official_masterlist
SET suffix = NULL,
    updated_at = NOW()
WHERE suffix IS NOT NULL
  AND TRIM(LOWER(suffix)) IN ('not applicable', 'not apllicable', 'na');

COMMIT;
